### ISSUE TITLE
Assigning "Subiect" to "Cercetator" fails with internal server error

### ISSUE THREAD

**Issue by darakna** [it-pebune/ani-research-backend#47]
Steps:

1. Go to QA env: https://cercetare-qa.integritatepebune.ro/
2. Login with a user with coordinator role. ex: anipebunetestuser3
3. Press on "Subiecti" button
4. Pick a subject, press on action menu button and select "Asigneaza". From the pop-up list select a user with proper rights and press "Asigneaza" button.
5. In console notice the PUT api call is returning internal server error [500]. Notice that the "ASIGNAT CATRE" field is populated with the appropriate name but after reload the data will be the same as the initial value.

Tested on
QA ENV
Backend version: {"v":"0.9.0"}
Frontend version: unknown - Merge pull request https://github.com/it-pebune/ani-research-web/pull/80

![image](https://user-images.githubusercontent.com/10879532/158082753-2a76926f-c3e5-4ed7-84de-4df070d493f5.png)

**Comment by Devtronyx** [comment]
Fixed. Latest version of a stored procedure needed to be run
