### ISSUE TITLE
[BUG]: [User Profile] User name with diacritics is not displayed properly

### ISSUE THREAD

**Issue by catalin-apostu** [it-pebune/ani-research-backend#60]
### Describe the Bug

In the profile of the logged user, when using a name with diacritics for editing, like Ionuț, the name is not saved properly.

### Steps to Reproduce

1. Go to the user profile of the logged user
2. Click on edit profile
3. Introduce a name with diacritics as First Name / Last Name / Display Name, e.g. Ionuț
4. Save

The diacritics in the name are not displayed properly.

### Environment

```markdown
- OS: macos
- Browser: firefox
- Version:
- App Version:
```

**Comment by endriu3314** [comment]
From what I've debugged, It looks like the backend sends it back without diacritics.

https://github.com/it-pebune/ani-research-backend/blob/bdc6098b64e5446ec42fc82926277ddbcac8ba4e/sqls/db/create-test-db.sql#L16

From what I can see here the DB uses `SQL_Latin1_General_CP1_CI_AS` Collate.
Here it says that https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver15 that COLLATION supports English so I may just assume that diacritics never actually reach the database.

@Devtronyx can you confirm?
